# Generated by Django 4.2.4 on 2023-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_post_story_delete_question_post_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
